name: vybe
options:
  bundleIdPrefix: com.kkim
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  vybe:
    type: application
    platform: iOS
    sources:
      - path: vybe
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kkim.vybe
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: "vybe"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "vybe uses your location to show nearby listings and meetup spots."
        INFOPLIST_KEY_NSCameraUsageDescription: "vybe needs camera access to take photos of items you want to sell."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "vybe needs photo library access to select images for your listings."
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: true
        SWIFT_EMIT_LOC_STRINGS: true

  vybeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: vybeTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: vybe
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kkim.vybeTests
        GENERATE_INFOPLIST_FILE: true
